version: '3.9'

services:

  server:
    build: ./server
    container_name: server
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
#   environment:
#     PORT: 5000
#     PROTOCOL: http
#     HOST: localhost
#     SWAGGER_URL: docs
#     DATABASE_URL: postgresql://postgres:postgres@jetup_db/test?schema=public
    links:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./client
    container_name: app
    restart: on-failure
    ports:
      - 3000:3000
    env_file:
      - ./client/.env

volumes:
  postgres_data: