version: "3.9"

services:

  server:
    build: server/
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - server/.env.example
#    environment:
#      PORT: 5000
#      PROTOCOL: http
#      HOST: localhost
#      SWAGGER_URL: docs
#      DATABASE_URL: postgresql://postgres:postgres@jetup_db/jetup?schema=public
    links:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    container_name: db-postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - server/.env.example

