version: '3.9'

services:

  server:
    build: ./server
    container_name: server
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/server
    links:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile_dev
    container_name: web
    restart: on-failure
    depends_on:
      - server
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app
#     - /usr/src/app/node_modules

volumes:
  postgres_data: